# Generated by Django 4.2.6 on 2023-10-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='Конец',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='Начало',
            new_name='startdate',
        ),
    ]
