# Generated by Django 4.2.6 on 2023-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_games_friendlyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='enddate',
            field=models.DateField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='games',
            name='startdate',
            field=models.DateField(auto_now_add=True, verbose_name='Начало'),
        ),
    ]
