# Generated by Django 4.2.6 on 2023-10-31 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_alter_games_enddate_alter_games_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='Ответ',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
