# Generated by Django 4.2.6 on 2023-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_games_friendlyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='friendlyname',
            field=models.CharField(max_length=24, verbose_name='Название игры'),
        ),
    ]
