# Generated by Django 4.2.6 on 2023-11-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_games_friendlyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='enddate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='startdate',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.CharField(default='9MO6ne', editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='Id игры'),
        ),
    ]
