# Generated by Django 4.2.6 on 2023-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_enddate_games_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.CharField(default='SxJ278', editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='Id игры'),
        ),
    ]
