# Generated by Django 4.2.6 on 2023-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_games_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.CharField(default='qX57ul', editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='Id игры'),
        ),
    ]
