# Generated by Django 4.2.6 on 2023-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_games_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id игры'),
        ),
    ]
