# Generated by Django 4.2.6 on 2023-11-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_games_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='end',
            field=models.DateTimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='games',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало'),
        ),
    ]
