# Generated by Django 4.2.6 on 2023-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_games_end_alter_games_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Статус игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='start',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
    ]
