# Generated by Django 4.2.6 on 2023-10-31 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя')),
                ('firstname', models.CharField(max_length=32, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('password', models.CharField(help_text='Пароль', max_length=128, verbose_name='Пароль')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
