# Generated by Django 4.2.6 on 2023-10-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_is_authenticated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
