# Generated by Django 4.2.6 on 2023-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wins',
            field=models.PositiveIntegerField(default=0, help_text='Победы', verbose_name='Победы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=16, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
